### ISSUE TITLE
BIDS to nnUNet V2 new version based on Jan pull request #11

### ISSUE THREAD

**Issue by tzebre** [ivadomed/data-conversion#12]
### NOTE
ℹ️ Further discussion moved to the associated PR https://github.com/ivadomed/data-conversion/pull/13

----

@valosekj  started a pull request #11 # to create a script for converting BIDS to nnUNetV2 records. 

I'm modifying this pull request in [my branch](https://github.com/ivadomed/data-conversion/blob/tm_update_nnunet_conversion_script_to_v2/dataset_conversion/convert_bids_to_nnUnetv2.py)
Here are the changes that seem relevant to me : 

- [x] Do TODO task (duplication refactoring) from Jan code 
  - Done in [convert_subject function](https://github.com/ivadomed/data-conversion/blob/31144e82500b03610b907ad31d872097e2e7a939/dataset_conversion/convert_bids_to_nnUnetv2.py#LL84C12-L84C12) 

- [x] Manage the suffix label:
  - Check if this suffix label exists in the derivatives (prevent symlink from pointing to nothing)
  - Make suffix label optional in case we only want to convert data without ground truth 

- [x] Accept case without splitting into train/validation (not sure if relevant)  

- [ ] Modify dataset.json to comply with V2 requirements

  - [x] Remove old attribute not used anymore 
  - [ ] Create channel name depending on contrast given in argument, add possibility to give multiple contrasts too 
  - [ ] Adapt code to accept labeled image with different integer ("background" = 0, "lesion" = 1, "CSF"= 2 ...)

Ideas:
- Add ability to reorient image with argument (not sure if it's relevant in a general purpose script)
- Ability to add images to an already existing dataset (since nnUNet uses only one dataset, if you want to use different BIDS different datasets they have to be merged in unique nnUNet one ). 

_if you have any comments on the todo list or any other ideas, please don't hesitate to contact me._

**Comment by valosekj** [comment]
Thank you for taking a look! 💯 
I took the liberty and moved the content of your comment into https://github.com/ivadomed/data-conversion/pull/13 to allow easy code review. We can continue the discussion there.
